[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs",
  "storage-proofs/core",
  "storage-proofs/porep",
  "storage-proofs/post",
  "fil-proofs-tooling",
  "sha2raw"
]

[patch.crates-io]
#bellperson = { git = "https://github.com/Krysme/bellperson" }
bellperson = { path = "../my-bellman" }
neptune = { path = "../my-neptune" }