[workspace]

members = [
  "filecoin-proofs",
]

[patch.crates-io]
bellperson = { path = "../my-bellman" }
neptune = { path = "../my-neptune" }
phase21 = { git = "https://github.com/Krysme/phase2", branch = "master" }
